version: '3.8'

services:
  web:
    build: .
    entrypoint: ./entrypoint.dev.sh
    volumes:
      - ./:/opt/backend
    ports:
      - 8004:8000
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: